import '../../styles/globals.css';
import styles from '../../styles/Home.module.css';
export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default function Layout({ children }) {
    return <div className={styles.container}>{children}</div>;
}
